apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-prometheus-demo
spec:
  selector:
    matchLabels:
      run: demo-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        run: demo-prometheus
    spec:
      containers:
      - name: demo-prometheus
        image: iimnd/golang-prometheus:latest
        env:
        - name: VERSION
          value: 0.1.0
        ports:
        - containerPort: 9001
        
---

apiVersion: v1
kind: Service
metadata:
  name: golang-prometheus-demo-svc
spec:
  type: ClusterIP
  selector:
    run: demo-prometheus
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
