apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-prometheus-demo
spec:
  selector:
    matchLabels:
      run: demo-prometheus
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
      labels:
        run: demo-prometheus
    spec:
      containers:
      - name: demo-prometheus
        image: iimnd/golang-prometheus:2.0.0
        env:
        - name: VERSION
          value: 2.0.1
        ports:
        - containerPort: 9001
        
---

apiVersion: v1
kind: Service
metadata:
  name: golang-prometheus-demo-svc
spec:
  type: ClusterIP
  selector:
    run: demo-prometheus
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
