global:
  evaluation_interval: 1m
  external_labels:
    cluster_id: cluster-one
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'architect-frontend-exporter'
  metrics_path: "/frontend_metrics"
  static_configs:
  - targets:
    - localhost:9001
- job_name: 'architect-go-exporter'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: k8s_pod_name
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - action: labeldrop
    regex: '(kubernetes_pod|app_kubernetes_io_instance|app_kubernetes_io_name|instance)'
