apiVersion: batch/v1
kind: Job
metadata:
  name: golang-prome-performance-test
spec:
  template:
    spec:
      containers:
      - name: golang-prome-performance-test
        image: loadimpact/k6:0.33.0
        command: ["k6",  "run", "--out", "influxdb=http://103.117.207.239:8086/test_k6","/app/soak-test-golang-prome.js"]
        volumeMounts:
        - name: my-volume
          mountPath: /app
      volumes:
      - name: my-volume
        configMap:
         name: soak-test-golang-prome
      restartPolicy: Never


